import { NextRequest, NextResponse } from "next/server";
import { getPayload } from "payload";
import config from "@payload-config";

// POST - Bulk import registrations from CSV
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ slug: string }> }
) {
  try {
    const payload = await getPayload({ config });
    const { slug } = await params;

    // Find the event
    const events = await payload.find({
      collection: "managed-events",
      where: { slug: { equals: slug } },
      limit: 1,
    });

    if (events.docs.length === 0) {
      return NextResponse.json({ error: "Event not found" }, { status: 404 });
    }

    const event = events.docs[0] as unknown as {
      id: string;
      title?: string;
      maxCapacity?: number;
    };

    // Get current confirmed count to check capacity
    const currentCount = await payload.count({
      collection: "event-registrations",
      where: {
        event: { equals: event.id },
        status: { in: ["registered", "confirmed", "attended", "baptized"] },
      },
    });

    const formData = await request.formData();
    const file = formData.get("file") as File | null;
    const skipDuplicates = formData.get("skipDuplicates") === "true";
    const sendConfirmation = formData.get("sendConfirmation") === "true";

    if (!file) {
      return NextResponse.json({ error: "No file provided" }, { status: 400 });
    }

    // Read and parse CSV
    const text = await file.text();
    const lines = text.split("\n").filter((line) => line.trim());

    if (lines.length < 2) {
      return NextResponse.json(
        { error: "CSV must have a header row and at least one data row" },
        { status: 400 }
      );
    }

    // Parse header
    const header = parseCSVLine(lines[0]);
    const columnMap = mapColumns(header);

    if (!columnMap.name) {
      return NextResponse.json(
        { error: "CSV must have a 'name' or 'guestName' column" },
        { status: 400 }
      );
    }

    // Parse data rows
    const results = {
      total: 0,
      imported: 0,
      skipped: 0,
      errors: [] as Array<{ row: number; name: string; error: string }>,
      waitlisted: 0,
    };

    const availableSpots = event.maxCapacity
      ? event.maxCapacity - currentCount.totalDocs
      : Number.POSITIVE_INFINITY;
    let confirmedCount = 0;

    // Get current max waitlist position
    const maxWaitlistPos = await payload.find({
      collection: "event-registrations",
      where: {
        event: { equals: event.id },
        status: { equals: "waitlisted" },
      },
      sort: "-waitlistPosition",
      limit: 1,
    });
    let waitlistPosition =
      maxWaitlistPos.docs.length > 0
        ? ((maxWaitlistPos.docs[0] as unknown as { waitlistPosition?: number })
            .waitlistPosition || 0) + 1
        : 1;

    for (let i = 1; i < lines.length; i++) {
      const line = lines[i].trim();
      if (!line) continue;

      results.total++;

      try {
        const values = parseCSVLine(line);
        const row = mapRowToObject(values, columnMap);

        if (!row.name) {
          results.errors.push({
            row: i + 1,
            name: "Unknown",
            error: "Missing name",
          });
          results.skipped++;
          continue;
        }

        // Check for duplicates by email
        if (skipDuplicates && row.email) {
          const existing = await payload.find({
            collection: "event-registrations",
            where: {
              event: { equals: event.id },
              "guestInfo.email": { equals: row.email },
            },
            limit: 1,
          });

          if (existing.docs.length > 0) {
            results.errors.push({
              row: i + 1,
              name: row.name,
              error: "Duplicate email - skipped",
            });
            results.skipped++;
            continue;
          }
        }

        // Determine status based on capacity
        const status =
          confirmedCount < availableSpots ? "registered" : "waitlisted";
        const currentWaitlistPosition =
          status === "waitlisted" ? waitlistPosition : null;

        if (status === "waitlisted") {
          results.waitlisted++;
          waitlistPosition++;
        } else {
          confirmedCount++;
        }

        // Create registration (inviteCode is auto-generated by the collection hook)
        const registration = await payload.create({
          collection: "event-registrations",
          data: {
            event: event.id,
            guestInfo: {
              name: row.name,
              email: row.email || undefined,
              phone: row.phone || undefined,
            },
            status,
            waitlistPosition: currentWaitlistPosition,
            registeredAt: new Date().toISOString(),
            notes: row.notes || undefined,
            importedAt: new Date().toISOString(),
          },
        });

        results.imported++;

        // Send confirmation email if requested and email exists
        if (sendConfirmation && row.email && process.env.RESEND_API_KEY) {
          try {
            const inviteCode = (registration as unknown as { inviteCode: string }).inviteCode;
            await sendConfirmationEmail(
              row.email,
              row.name,
              inviteCode,
              event,
              status
            );
          } catch (emailError) {
            console.error("Failed to send confirmation email:", emailError);
          }
        }
      } catch (error) {
        results.errors.push({
          row: i + 1,
          name: "Unknown",
          error: error instanceof Error ? error.message : "Unknown error",
        });
        results.skipped++;
      }
    }

    return NextResponse.json({
      success: true,
      message: `Successfully imported ${results.imported} registrations`,
      results,
    });
  } catch (error) {
    console.error("Import error:", error);
    return NextResponse.json(
      { error: "Failed to import registrations" },
      { status: 500 }
    );
  }
}

// Parse a CSV line handling quoted fields
function parseCSVLine(line: string): string[] {
  const result: string[] = [];
  let current = "";
  let inQuotes = false;

  for (let i = 0; i < line.length; i++) {
    const char = line[i];

    if (char === '"') {
      if (inQuotes && line[i + 1] === '"') {
        current += '"';
        i++;
      } else {
        inQuotes = !inQuotes;
      }
    } else if (char === "," && !inQuotes) {
      result.push(current.trim());
      current = "";
    } else {
      current += char;
    }
  }

  result.push(current.trim());
  return result;
}

// Map header columns to field names
function mapColumns(header: string[]): Record<string, number> {
  const map: Record<string, number> = {};

  const nameAliases = [
    "name",
    "guestname",
    "guest name",
    "full name",
    "fullname",
  ];
  const emailAliases = [
    "email",
    "guestemail",
    "guest email",
    "email address",
  ];
  const phoneAliases = [
    "phone",
    "guestphone",
    "guest phone",
    "phone number",
    "mobile",
  ];
  const notesAliases = ["notes", "note", "comments", "comment"];

  header.forEach((col, index) => {
    const normalized = col.toLowerCase().trim().replace(/['"]/g, "");

    if (nameAliases.includes(normalized)) {
      map.name = index;
    } else if (emailAliases.includes(normalized)) {
      map.email = index;
    } else if (phoneAliases.includes(normalized)) {
      map.phone = index;
    } else if (notesAliases.includes(normalized)) {
      map.notes = index;
    }
  });

  return map;
}

// Map row values to object using column map
function mapRowToObject(
  values: string[],
  columnMap: Record<string, number>
): Record<string, string> {
  const obj: Record<string, string> = {};

  if (columnMap.name !== undefined) {
    obj.name = values[columnMap.name] || "";
  }
  if (columnMap.email !== undefined) {
    obj.email = values[columnMap.email] || "";
  }
  if (columnMap.phone !== undefined) {
    obj.phone = values[columnMap.phone] || "";
  }
  if (columnMap.notes !== undefined) {
    obj.notes = values[columnMap.notes] || "";
  }

  return obj;
}

// Send confirmation email
async function sendConfirmationEmail(
  email: string,
  name: string,
  inviteCode: string,
  event: { title?: string },
  status: string
) {
  const { Resend } = await import("resend");
  const resend = new Resend(process.env.RESEND_API_KEY);
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://pmcc4thwatch.us";

  await resend.emails.send({
    from: process.env.EMAIL_FROM || "PMCC 4th Watch <events@pmcc4thwatch.us>",
    to: email,
    subject:
      status === "registered"
        ? `Registration Confirmed: ${event.title}`
        : `You're on the Waitlist: ${event.title}`,
    html: `
      <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
        <h1 style="color: #1e3a5f;">Hello ${name}!</h1>
        <p>You have been registered for <strong>${event.title}</strong>.</p>
        ${
          status === "waitlisted"
            ? `<p style="color: #f59e0b; font-weight: bold;">You are currently on the waitlist. We'll notify you if a spot opens up.</p>`
            : `<p>Your registration is <strong style="color: #22c55e;">confirmed</strong>!</p>
             <p style="font-size: 1.25rem; padding: 1rem; background: #f8f6f3; border-radius: 8px; text-align: center;">
               Your ticket code: <strong>${inviteCode}</strong>
             </p>
             <p>
               <a href="${baseUrl}/ticket/${inviteCode}" style="display: inline-block; padding: 12px 24px; background: #c9a227; color: #1e3a5f; text-decoration: none; border-radius: 25px; font-weight: bold;">
                 View Your Ticket
               </a>
             </p>`
        }
        <p>We look forward to seeing you!</p>
      </div>
    `,
  });
}

// GET - Return a sample CSV template
export async function GET() {
  const template = `name,email,phone,notes
John Doe,john@example.com,+1-555-0100,First time visitor
Jane Smith,jane@example.com,+1-555-0101,Returning member
Bob Johnson,bob@example.com,+1-555-0102,Needs wheelchair access`;

  return new NextResponse(template, {
    headers: {
      "Content-Type": "text/csv",
      "Content-Disposition": 'attachment; filename="import-template.csv"',
    },
  });
}
